### ISSUE TITLE
Explorer support for Nakamoto + sBTC

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/explorer#1205]
Track sBTC-related work in Explorer:

- [x] [Create an FT page](https://github.com/hirosystems/explorer/issues/1204)
- [ ] [Add signer information to the sBTC FT page](https://github.com/hirosystems/explorer/issues/1248)

Not necessary for sBTC, but nice to have:
- [x] [List all SIP-10 tokens +  search capability](https://github.com/hirosystems/explorer/issues/1088) depends on [this API issue](https://github.com/hirosystems/token-metadata-api/issues/170)
- [ ] Search transactions by memos

**Comment by andresgalante** [comment]
Related https://github.com/hirosystems/explorer/issues/1248

**Comment by eugeniadigon** [comment]
Related https://github.com/hirosystems/explorer/issues/1328 (sBTC transaction types)

**Comment by andresgalante** [comment]
Signer page and blocks pages are ready, we'll open a new issue when we start working on sBTC
